# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cityname', models.CharField(choices=[('TP', 'taipei'), ('TC', 'taichung'), ('TY', 'taoyuan'), ('YL', 'yilan')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtname', models.CharField(choices=[('GG', 'gongguan')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('contentforpost', models.CharField(max_length=500)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('wifi', models.BooleanField()),
                ('address', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('worktime', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
